site_name: CARLA 深度强化学习自动驾驶系统
site_description: 基于 CARLA Simulator 的强化学习自动驾驶项目
site_author: 花降らし
site_url: https://github.com/OpenHUTB/nn

nav:
  - 首页: index.md

theme:
  name: material
  language: zh
  palette:
    primary: blue
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
  - fenced_code
  - tables
  - admonition
  - codehilite

repo_name: OpenHUTB/nn
repo_url: https://github.com/OpenHUTB/nn